micronaut:
  application:
    name: aluraFlix
datasources:
  default:
    url: jdbc:mysql://localhost:3306/aluraflix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    schema-generate: CREATE_DROP
    dialect: MYSQL
#jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    entity-scan:
      packages: 'github.com.daniloandrade.models'


flyway:
  datasources:
    default:
      enabled: true
